# single test suite, non-parallel build.


language: ruby
rvm:
 - 2.3.3
install:
- bundle install


env:
  global:
    - CC_TEST_REPORTER_ID=ABC123

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
