env:
  global:
    - CC_TEST_REPORTER_ID=18d27d844a8c6524d5c2fa59a73488371c75dee2c7dbb7ea7434dcc602a8dffa
    
language: ruby
rvm:
 - 2.3.3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - './cc-test-reporter before-build'
after_script:
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
